version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello,"

  say-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say world"
          command: echo World! aka ${PLANET_NAME}

  another_job:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.co.ke/"
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

workflows:
  say-hello-world-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello
      - another_job
      - smoke_test:
          requires:
            - another_job
