version: 2.1 

commands:
  print_pipeline_id:
    parameters:
      id: 
        type: string
    steps:
      - run: echo << parameters.id >>

jobs:
  say-hello: 
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello,"
  say-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say world"
          command: echo World! aka ${PLANET_NAME}
  another_job:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
workflows:
  say-hello-world-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello
      - another_job
      
