version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>

  destroy_environment:
    steps:
      - run:
          name: Destroy Environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello,"

  say-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say world"
          command: echo World! aka ${PLANET_NAME}

  another_job:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>

  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Infra
          command: |
            aws cloudformation deploy \
            --stack-name myStack \
            --template-file template.yml  \
            --region=us-east-1

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: smoke test
          command: |
            return 1
      - destroy_environment 

workflows:
  setup-infra-workflow:
    jobs:
      - create_infra
      - smoke_test:
          requires:
            - create_infra
